export default {
  login: 'john-smilga',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/john-smilga',
  html_url: 'https://github.com/john-smilga',
  followers_url: 'https://api.github.com/users/john-smilga/followers',
  following_url:
    'https://api.github.com/users/john-smilga/following{/other_user}',
  gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://api.github.com/users/john-smilga/repos',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'John Smilga',
  company: 'Coding Addict',
  blog: 'www.johnsmilga.com',
  location: 'Los Angeles',
  email: null,
  hireable: null,
  bio: 'Creator of Coding Addict',
  twitter_username: 'john_smilga',
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
};


// {
//   "login": "shubhamrawatktw",
//   "id": 103437893,
//   "node_id": "U_kgDOBipWRQ",
//   "avatar_url": "https://avatars.githubusercontent.com/u/103437893?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/shubhamrawatktw",
//   "html_url": "https://github.com/shubhamrawatktw",
//   "followers_url": "https://api.github.com/users/shubhamrawatktw/followers",
//   "following_url": "https://api.github.com/users/shubhamrawatktw/following{/other_user}",
//   "gists_url": "https://api.github.com/users/shubhamrawatktw/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/shubhamrawatktw/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/shubhamrawatktw/subscriptions",
//   "organizations_url": "https://api.github.com/users/shubhamrawatktw/orgs",
//   "repos_url": "https://api.github.com/users/shubhamrawatktw/repos",
//   "events_url": "https://api.github.com/users/shubhamrawatktw/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/shubhamrawatktw/received_events",
//   "type": "User",
//   "site_admin": false,
//   "name": "Shubham rawat",
//   "company": null,
//   "blog": "",
//   "location": null,
//   "email": null,
//   "hireable": null,
//   "bio": null,
//   "twitter_username": null,
//   "public_repos": 12,
//   "public_gists": 0,
//   "followers": 1,
//   "following": 3,
//   "created_at": "2022-04-11T14:34:59Z",
//   "updated_at": "2022-04-28T12:38:55Z"
//   }